server:
  port: 8662

spring:
  application:
    name: gateway-service
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    micro-service:
      path: /call/**
      serviceId: micro-service
      stripPrefix: true
    micro-to-micro-service:
      path: /doublecall/**
      serviceId: micro-to-micro-service
      stripPrefix: true
      
ribbon:
  eureka:
    enabled: false

micro-service:
  ribbon:
    listOfServers: http://localhost:8183,http://localhost:8184
