server:
  port: 8080

spring:
  application:
    name: zuul
  cloud:
    config:
      uri: http://localhost:9999
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
